export const UPDATE_SEARCH_TERM = 'UPDATE_SEARCH_TERM';

export const CREATE_NOTE = 'CREATE_NOTE';
export const REMOVE_NOTE = 'REMOVE_NOTE';
export const CHANGE_SUBJECT = 'CHANGE_SUBJECT';
export const CHANGE_BODY = 'CHANGE_BODY';
